#!/usr/bin/bash

# Update package lists
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Backup the default HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Create a new HAProxy configuration file

config=\
"
frontend http_front
    bind *:80
    mode http
    default_backend http_back
backend http_back
    balance roundrobin
    server 229478-web-01 54.144.147.222:80 check
    server 229478-web-02 34.202.164.9:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
