#!/usr/bin/env bash
# This script is displaying Best School 10 times and hi at the 9th time

i=0

while [ $i -le 9 ]
do
    echo "Best School"
    if [ $i -eq 8 ]
    then
        echo "Hi"
    fi
    ((i++))
done
